[package]
name = "tts-helper"
version = "0.0.0"
description = "A Tauri App"
authors = ["Dylan Warren (https://github.com/Uhuh)"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.2", features = [] }

[dependencies]
tauri = { version = "1.2", features = ["shell-open"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rodio = "0.17.1"
reqwest = "0.11.16"
anyhow = "1.0.70"
bytes = "1"
thiserror = "1"
crossbeam = "0.8"

# Web server
tokio = { version = "1", features = ["rt"] }
axum = { version = "0.6", default-features = false, features = [
    "http1",
    "tokio",
    "tracing",
] }

# Tracing
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
